### ISSUE TITLE
Error: P1000: Authentication failed against database server at `menufic-db`

### ISSUE THREAD

**Issue by Revdep** [kaje94/menufic#8]
Bug (?)

## What is the current behavior?
I'm trying to install menufic with docker-compose method. That's my docker-compose.yml
```
version: "3.6"

services:

  menufic:
    image: l4rm4nd/menufic:latest
    container_name: menufic
    env_file:
      - menufic.env
      - .env
    expose:
      - 3000
    ports:
      - 3010:3000
    restart: unless-stopped
    networks:
      - backend

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: menufic-db
    env_file:
      - .env
    expose:
      - 3306
    ports:  
      - 3006:3306
    volumes:
      - .config/mariadb:/config
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    external: true
```

> .env file:

```
NODE_ENV=production
SKIP_ENV_VALIDATION=true


DATABASE_URL=mysql://XXX:XXX@menufic-db:3306/menufic_db

NEXTAUTH_URL=http://localhost:3010
NEXTAUTH_SECRET=


GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""


IMAGEKIT_PUBLIC_KEY=public_XXX
IMAGEKIT_PRIVATE_KEY=private_XXX
NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT=https://ik.imagekit.io/XXX/
IMAGEKIT_BASE_FOLDER=menufic-local

NEXT_PUBLIC_MAX_RESTAURANTS_PER_USER=5
NEXT_PUBLIC_MAX_MENUS_PER_RESTAURANT=5
NEXT_PUBLIC_MAX_CATEGORIES_PER_MENU=10
NEXT_PUBLIC_MAX_MENU_ITEMS_PER_CATEGORY=20
NEXT_PUBLIC_MAX_BANNERS_PER_RESTAURANT=5

NEXT_PUBLIC_CONTACT_EMAIL=XXX

TEST_MENUFIC_USER_LOGIN_KEY=a_string_value
TEST_MENUFIC_BASE_URL=http://localhost:3000


NEXT_PUBLIC_PROD_URL=https://menu.XXX.com
```

`docker-compose up -d `
in the logs you'll see:

> Error: P1000: Authentication failed against database server at `menufic-db`, the provided database credentials for `XXX` are not valid.

-------------------------------------------------------------------------------

i tried also to inser the options
```
username=
password=''
```

inside .config/mariadb/custom.cnf
with same result.

I did something wrong or this is a bug?
